const techStack = [
  { id: '1', tech: 'PHP' },
  { id: '2', tech: 'Laravel' },
  { id: '3', tech: 'MERN' },
  { id: '4', tech: '.NET' },
  { id: '5', tech: 'React' },
  { id: '6', tech: 'Node.js' },
  { id: '7', tech: 'MongoDB' },
  { id: '8', tech: 'Express' },
  { id: '9', tech: 'Tailwind CSS' },
  { id: '10', tech: 'TypeScript' },
  { id: '11', tech: 'JavaScript' },
  { id: '12', tech: 'GraphQL' },
  { id: '13', tech: 'AWS' },
  { id: '14', tech: 'Azure' },
  { id: '15', tech: 'GCP' },
  { id: '16', tech: 'Docker' },
  { id: '17', tech: 'Kubernetes' },
  { id: '18', tech: 'Jest' },
  { id: '19', tech: 'Python' },
  { id: '20', tech: 'Django' },
  { id: '21', tech: 'Flask' },
  { id: '22', tech: 'Java' },
  { id: '23', tech: 'Spring Boot' },
  { id: '24', tech: 'Ruby on Rails' },
  { id: '25', tech: 'C#' },
  { id: '26', tech: 'SQL' },
  { id: '27', tech: 'PostgreSQL' },
  { id: '28', tech: 'MySQL' },
  { id: '29', tech: 'SQL Server' },
  { id: '30', tech: 'Redis' },
  { id: '31', tech: 'Elasticsearch' },
  { id: '32', tech: 'Vue.js' },
  { id: '33', tech: 'Angular' },
  { id: '34', tech: 'SASS' },
  { id: '35', tech: 'Webpack' },
  { id: '36', tech: 'Git' },
  { id: '37', tech: 'CI/CD' },
  { id: '38', tech: 'Jenkins' },
  { id: '39', tech: 'Terraform' },
  { id: '40', tech: 'Linux' },
  { id: '41', tech: 'Shell Scripting' },
  { id: '42', tech: 'Firebase' },
  { id: '43', tech: 'Next.js' },
  { id: '44', tech: 'NestJS' },
  { id: '45', tech: 'Swift' },
  { id: '46', tech: 'Kotlin' },
  { id: '47', tech: 'Android' },
  { id: '48', tech: 'iOS' },
  { id: '49', tech: 'Flutter' },
  { id: '50', tech: 'React Native' },
  { id: '51', tech: 'OAuth2' },
  { id: '52', tech: 'JWT' },
  { id: '53', tech: 'Docker Compose' },
  { id: '54', tech: 'Nginx' },
  { id: '55', tech: 'Apache' },
  { id: '56', tech: 'TypeORM' },
  { id: '57', tech: 'Prisma' },
  { id: '58', tech: 'Knex.js' },
  { id: '59', tech: 'Sequelize' },
  { id: '60', tech: 'Bash' },
  { id: '61', tech: 'C++' },
  { id: '62', tech: 'PERN' },
  { id: '63', tech: 'RESTful API' },
  { id: '64', tech: 'Bootstrap' },
  { id: '65', tech: 'MUI' },
  { id: '66', tech: 'Ant Design' },
  { id: '67', tech: 'ReactJS' },
  { id: '68', tech: 'WordPress' },
  { id: '69', tech: 'Shopify' },
  { id: '70', tech: 'WooCommerce' },
  { id: '71', tech: 'Symfony' },
  { id: '72', tech: 'CakePHP' },
  { id: '73', tech: 'Joomla' },
  { id: '74', tech: 'Magento' },
  { id: '75', tech: 'Zend Framework' },
  { id: '76', tech: 'Cordova' },
  { id: '77', tech: 'Electron' },
  { id: '78', tech: 'Salesforce' },
  { id: '79', tech: 'Spring Security' },
  { id: '80', tech: 'RabbitMQ' },
  { id: '81', tech: 'Apache Kafka' },
  { id: '82', tech: 'OpenShift' },
  { id: '83', tech: 'ElasticSearch' },
  { id: '84', tech: 'HTML5' },
  { id: '85', tech: 'CSS3' },
  { id: '86', tech: 'Postman' },
];

export default techStack;
