name: CI

on:
  pull_request:
    branches:
      - '**'

jobs:
  lint-and-test:
    environment: dev
    timeout-minutes: 5
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_SENTRY_DSN: ${{ secrets.NEXT_PUBLIC_SENTRY_DSN }}
      NEXT_PUBLIC_APP_BASE_URL: ${{ secrets.NEXT_PUBLIC_APP_BASE_URL }}
      NEXT_PUBLIC_LOG_ROCKET_ID: ${{ secrets.NEXT_PUBLIC_LOG_ROCKET_ID }}
      NEXT_PUBLIC_FIREBASE_APP_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_APP_ID }}
      NEXT_PUBLIC_RQH_API_BASE_URL: ${{ secrets.NEXT_PUBLIC_RQH_API_BASE_URL }}
      NEXT_PUBLIC_FIREBASE_API_KEY: ${{ secrets.NEXT_PUBLIC_FIREBASE_API_KEY }}
      NEXT_PUBLIC_PORTAL_API_BASE_URL: ${{ secrets.NEXT_PUBLIC_PORTAL_API_BASE_URL }}
      NEXT_PUBLIC_FIREBASE_PROJECT_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_PROJECT_ID }}
      NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID }}
      NEXT_PUBLIC_INTERCOM_APP_ID: ${{ secrets.NEXT_PUBLIC_INTERCOM_APP_ID }}
      NEXT_PUBLIC_INTERCOM_API_BASE_URL: ${{ secrets.NEXT_PUBLIC_INTERCOM_API_BASE_URL }}
      NEXT_PUBLIC_GA_ID: ${{ secrets.NEXT_PUBLIC_GA_ID }}
      APP_ENV: staging
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: 'npm'
          node-version-file: '.nvmrc'
      - name: Install dependencies
        run: npm ci --ignore-scripts
      - name: ESLint & Prettier
        run: npm run lint
      - name: Test
        run: npm run test